require "bundler"
Bundler.setup

def current_env
  ENV["RACK_ENV"] ||= "development"
end

begin
  require 'sequent/rake/tasks'
  require_relative 'invoicing_app'
  Sequent::Rake::Tasks.new({
    db_config_supplier: InvoicingApp::DB_CONFIG,
    view_projection: InvoicingApp::VIEW_PROJECTION,
    event_store_schema: 'event_store',
    environment: ENV['RACK_ENV'] || 'development'
  }).register!
rescue LoadError
  puts 'Sequent tasks are not available'
end
