source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem 'rake'
# let's use the latest and greatest
gem 'sequent', github: 'zilverline/sequent'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'activemodel'
gem 'webrick'

group :test do
  gem 'rspec'
  gem 'database_cleaner'
end
