name: rspec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  POSTGRES_USER: sequent
  POSTGRES_PASSWORD: sequent

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: sequent
          POSTGRES_PASSWORD: sequent
          POSTGRES_DB: blog_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./building-a-web-application
          bundler-cache: true

      - name: Run building-a-web-application tests
        working-directory: ./building-a-web-application
        run: bundle exec rspec
